// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_opensim_compiled
bool cpp_opensim_compiled();
RcppExport SEXP _PhysioOpenSim_cpp_opensim_compiled() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_compiled());
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_build_config
Rcpp::List cpp_opensim_build_config();
RcppExport SEXP _PhysioOpenSim_cpp_opensim_build_config() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_build_config());
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_version
Rcpp::List cpp_opensim_version();
RcppExport SEXP _PhysioOpenSim_cpp_opensim_version() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_version());
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_model_summary
Rcpp::List cpp_opensim_model_summary(const std::string& path);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_summary(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_model_summary(path));
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_model_load
SEXP cpp_opensim_model_load(const std::string& path);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_load(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_model_load(path));
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_model_is_initialized
bool cpp_opensim_model_is_initialized(SEXP model_ptr);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_is_initialized(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_model_is_initialized(model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_model_init
bool cpp_opensim_model_init(SEXP model_ptr);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_init(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_model_init(model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_model_summary_ptr
Rcpp::List cpp_opensim_model_summary_ptr(SEXP model_ptr);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_summary_ptr(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_model_summary_ptr(model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_model_components
Rcpp::List cpp_opensim_model_components(SEXP model_ptr);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_components(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_model_components(model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_model_get_name
std::string cpp_opensim_model_get_name(SEXP model_ptr);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_get_name(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_model_get_name(model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// cpp_opensim_model_set_name
void cpp_opensim_model_set_name(SEXP model_ptr, const std::string& name);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_set_name(SEXP model_ptrSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type name(nameSEXP);
    cpp_opensim_model_set_name(model_ptr, name);
    return R_NilValue;
END_RCPP
}
// cpp_opensim_model_finalize_connections
void cpp_opensim_model_finalize_connections(SEXP model_ptr);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_finalize_connections(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    cpp_opensim_model_finalize_connections(model_ptr);
    return R_NilValue;
END_RCPP
}
// cpp_opensim_model_save
void cpp_opensim_model_save(SEXP model_ptr, const std::string& output_file);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_model_save(SEXP model_ptrSEXP, SEXP output_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_file(output_fileSEXP);
    cpp_opensim_model_save(model_ptr, output_file);
    return R_NilValue;
END_RCPP
}
// cpp_opensim_run_tool_native
Rcpp::List cpp_opensim_run_tool_native(const std::string& setup_file, const std::string& tool);
RcppExport SEXP _PhysioOpenSim_cpp_opensim_run_tool_native(SEXP setup_fileSEXP, SEXP toolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type setup_file(setup_fileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type tool(toolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_opensim_run_tool_native(setup_file, tool));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PhysioOpenSim_cpp_opensim_compiled", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_compiled, 0},
    {"_PhysioOpenSim_cpp_opensim_build_config", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_build_config, 0},
    {"_PhysioOpenSim_cpp_opensim_version", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_version, 0},
    {"_PhysioOpenSim_cpp_opensim_model_summary", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_summary, 1},
    {"_PhysioOpenSim_cpp_opensim_model_load", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_load, 1},
    {"_PhysioOpenSim_cpp_opensim_model_is_initialized", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_is_initialized, 1},
    {"_PhysioOpenSim_cpp_opensim_model_init", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_init, 1},
    {"_PhysioOpenSim_cpp_opensim_model_summary_ptr", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_summary_ptr, 1},
    {"_PhysioOpenSim_cpp_opensim_model_components", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_components, 1},
    {"_PhysioOpenSim_cpp_opensim_model_get_name", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_get_name, 1},
    {"_PhysioOpenSim_cpp_opensim_model_set_name", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_set_name, 2},
    {"_PhysioOpenSim_cpp_opensim_model_finalize_connections", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_finalize_connections, 1},
    {"_PhysioOpenSim_cpp_opensim_model_save", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_model_save, 2},
    {"_PhysioOpenSim_cpp_opensim_run_tool_native", (DL_FUNC) &_PhysioOpenSim_cpp_opensim_run_tool_native, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PhysioOpenSim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
