# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_opensim_compiled <- function() {
    .Call(`_PhysioOpenSim_cpp_opensim_compiled`)
}

cpp_opensim_build_config <- function() {
    .Call(`_PhysioOpenSim_cpp_opensim_build_config`)
}

cpp_opensim_version <- function() {
    .Call(`_PhysioOpenSim_cpp_opensim_version`)
}

cpp_opensim_model_summary <- function(path) {
    .Call(`_PhysioOpenSim_cpp_opensim_model_summary`, path)
}

cpp_opensim_model_load <- function(path) {
    .Call(`_PhysioOpenSim_cpp_opensim_model_load`, path)
}

cpp_opensim_model_is_initialized <- function(model_ptr) {
    .Call(`_PhysioOpenSim_cpp_opensim_model_is_initialized`, model_ptr)
}

cpp_opensim_model_init <- function(model_ptr) {
    .Call(`_PhysioOpenSim_cpp_opensim_model_init`, model_ptr)
}

cpp_opensim_model_summary_ptr <- function(model_ptr) {
    .Call(`_PhysioOpenSim_cpp_opensim_model_summary_ptr`, model_ptr)
}

cpp_opensim_model_components <- function(model_ptr) {
    .Call(`_PhysioOpenSim_cpp_opensim_model_components`, model_ptr)
}

cpp_opensim_model_get_name <- function(model_ptr) {
    .Call(`_PhysioOpenSim_cpp_opensim_model_get_name`, model_ptr)
}

cpp_opensim_model_set_name <- function(model_ptr, name) {
    invisible(.Call(`_PhysioOpenSim_cpp_opensim_model_set_name`, model_ptr, name))
}

cpp_opensim_model_finalize_connections <- function(model_ptr) {
    invisible(.Call(`_PhysioOpenSim_cpp_opensim_model_finalize_connections`, model_ptr))
}

cpp_opensim_model_save <- function(model_ptr, output_file) {
    invisible(.Call(`_PhysioOpenSim_cpp_opensim_model_save`, model_ptr, output_file))
}

cpp_opensim_run_tool_native <- function(setup_file, tool) {
    .Call(`_PhysioOpenSim_cpp_opensim_run_tool_native`, setup_file, tool)
}

